dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: mainnet-fork
  goerli:
    weth_token: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
  sepolia:
    explorer: https://api-sepolia.etherscan.io/api
    host: https://sepolia.infura.io/v3/3248eacd73a6414483cd73d32e31a3b4
    multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
    weth_token: "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"  
  mainnet-fork: 
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" 

wallets:
  from_key: ${PRIVATE_KEY}