dependencies:
  # - OpenZeppelin/openzeppelin-contracts@4.3.2
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      # - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env

networks:
  default: mainnet-fork  
  goerli:
  mainnet-fork: 
  sepolia:

wallets:
  from_key: ${PRIVATE_KEY}
