dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@chainlink='smartcontractkit/chainlink-brownie-contracts@1.1.1';
dotenv: .env
networks:
  default: mainnet-fork
  goerli:
    weth_token: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
  sepolia:
    weth_token: "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"  
    link_token: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
  mainnet-fork: 
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" 

wallets:
  from_key: ${PRIVATE_KEY}